razv/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('razvozki/', include('razvozki.urls')),
    path('admin/', admin.site.urls),
]

razvozki/urls.py
from django.urls import path, include

from . import views

app_name = 'razvozki'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete_rzv/<int:id>', views.delete_rzv, name='delete_rzv'),
    path('upd_rzv_txt', views.updrzv_txt),
    path('updaterecord_rzv', views.updaterecord_rzv, name='updaterecord_rzv'),
    path('main', views.main_rzv, name='main_rzv'),
    path('customers', views.customers, name='customers'),
    path('customers_clr', views.customers_clr, name='customers_clr'),
#    path('customers/addrecord_cst/', views.addrecord_cst, name='addrecord_cst'),
    path('customers/delete_cst/<int:id>', views.delete_cst, name='delete_cst'),
    path('updaterecord_cst', views.updaterecord_cst, name='updaterecord_cst'),
    path('print_rzv/<str:date_r>', views.print_rzv, name='print_rzv'),
    path('fulfilled_chg/<int:id>', views.fulfilled_chg, name='fulfilled_chg'),
    path('deliver_to/<int:id>', views.deliver_to, name='deliver_to'),
    path('return_all/<int:id>', views.return_all, name='return_all'),
    path('double/<order>', views.double, name='double'),
    path('double/unite_cst/', views.unite_cst, name='unite_cst'),
    path('admin', views.admin, name='admin'),
    path('import_csv', views.import_csv, name='import_csv'),
    path('import_cst', views.import_cst, name='import_cst'),
    path('delete_all_cst', views.delete_all_cst, name='delete_all_cst'),
    path('cst_double_search', views.cst_double_search, name='cst_double_search'),
    path('clean_rzv', views.clean_rzv, name='clean_rzv'),
    path('clean_cst', views.clean_cst, name='clean_cst'),
    path('export_rzv', views.export_rzv, name='export_rzv'),
    path('customers.xml', views.cust_xml, name='customers.xml'),
    path('<navi>', views.search_, name='search_'),
#    path('search_/<navi>', views.search_, name='search_'),
#    path('search_/search_/<navi>', views.search_, name='search_'),
#    path('customers/search_/<navi>', views.search_, name='search_'),
#    path('customers/search_/search_/<navi>', views.search_, name='search_'),
    path('rzv_return.xml/<int:id>', views.rzv_return_xml, name='rzv_return.xml'),

]

razvozki/models.py
import datetime
from django.utils import timezone
from django.db import models



class Customer(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    contact = models.CharField(max_length=255)
    mappoint = models.CharField(max_length=255, default='', help_text="Yandex mappoint")
    subcontractor = models.BooleanField(default=False, help_text='True if subcontractor')

    def __repr__(self):
        return f"Customer(name={self.name!r}, contact={self.contact!r})"

    def __str__(self):
        return self.name


class Customer_clr(Customer):
    clr = models.CharField(max_length=30, default='text-secondary')

    def __repr__(self):
        return f"Customer_clr(name={self.name!r}, contact={self.contact!r})"

    def __str__(self):
        return self.name


class Razvozka(models.Model):
    date = models.DateField(help_text='date of transportation')
    date_id = models.SmallIntegerField(default=0, help_text='order inside date')
    customer = models.ForeignKey(Customer, models.SET_NULL, null=True, blank=True, help_text='customer base if exist')
    customer_name = models.CharField(max_length=100, help_text='customer as text could differ from db')
    address = models.CharField(max_length=255, help_text='real address')
    contact = models.CharField(max_length=255, help_text='real contacts')
    to_do_deliver = models.CharField(max_length=255, help_text='things for delivery')
    to_do_take = models.CharField(max_length=255, help_text='things to take from')
    map_point = models.CharField(max_length=255, help_text='Yandex mappoint')
    clr = models.CharField(max_length=30, default='', help_text='text color')
    fulfilled = models.BooleanField(default=True, help_text='True is fulfilled')
    deliver_to = models.BooleanField(default=False, help_text='transportation to processing')
    return_from = models.BooleanField(default=False, help_text='return products from processing')
    return_all = models.BooleanField(default=False, help_text='False if some part was not return')
    return_goods = models.ForeignKey('self', models.SET_NULL, null=True, blank=True,
                                     help_text='from which delivery return')
    date_until = models.DateField(default='2022-08-01', null=True, blank=True, help_text='plan (last) date of transportation')
    date_create = models.DateField(default='2022-08-01', null=True, blank=True, help_text='date of create razvozka')



    def __str__(self):
        return str(self.date) + '| ' + str(self.customer_name) + '| ' + str(self.to_do_deliver)+ '| ' + str(self.to_do_take)

    def __repr__(self):
        return f"razvozka_list(date={self.date!r}, customer={self.customer_name!r}, deliver={self.to_do_deliver!r}, " \
               f"take={self.to_do_take!r}) "

    def get_all_todo(self):
        to_do_take = ''
        to_do_deliver = ''
        if self.to_do_take != '':
            to_do_take = ' ЗАБРАТЬ: ' + str(self.to_do_take)
        if self.to_do_deliver != '':
            to_do_deliver = ' СДАТЬ: ' + str(self.to_do_deliver)
        return f"{to_do_take} {to_do_deliver}"


class Razvozka_import (models.Model):
    date = models.DateField('date of transportation')
    date_id = models.SmallIntegerField(default=1)
    customer = models.ForeignKey(Customer_clr, models.SET_NULL, null=True, blank=True)
    customer_name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    contact = models.CharField(max_length=255)
    to_do_deliver = models.CharField(max_length=255, default='')
    to_do_take = models.CharField(max_length=255, default='')
    map_point = models.CharField(max_length=255)
    clr = models.CharField(max_length=30, default='')
    fulfilled = models.BooleanField(default=False)

    def __str__(self):
        return str(self.date) + '| ' + str(self.customer_name) + '| ' + str(self.to_do_deliver)+ '| ' + str(self.to_do_take)

    def __repr__(self):
        return f"razvozka_list(date={self.date!r}, customer={self.customer_name!r}, deliver={self.to_do_deliver!r}, " \
               f"take={self.to_do_take!r}) "

razvozki/views.py
# Create your views here.

import datetime

from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator
from .models import Razvozka, Customer, Customer_clr, Razvozka_import
from django.db.models import Q
from django.template import loader
from django.shortcuts import render
from django.http import Http404
from django.urls import reverse
from django.db import transaction
from django.core.files import File
from django.views.generic import ListView
from django.views.decorators.csrf import csrf_exempt



import csv


class Razvozka_clr:
    def __init__(self, id, date, date_id, customer, customer_name, address, contact, to_do_take, to_do_deliver,
                 clr):
        self.id = id
        self.date = date
        self.date_id = date_id
        self.customer = customer
        self.customer_name = customer_name
        self.address = address
        self.contact = contact
        self.to_do_take = to_do_take
        self.to_do_deliver = to_do_deliver
        self.clr = clr

    def get_all_todo_clr(self):
        to_do_take = ''
        to_do_deliver = ''
        if self.to_do_take != '':
            to_do_take = ' ЗАБРАТЬ: ' + str(self.to_do_take)
        if self.to_do_deliver != '':
            to_do_deliver = ' СДАТЬ: ' + str(self.to_do_deliver)
        return f"{to_do_take} {to_do_deliver}"


def index(request):
    navi = 'razvozka'
    datenew = datetime.date.today() + datetime.timedelta(days=1)
    dateold = datetime.date.today() - datetime.timedelta(days=3)
    datenew = datenew.strftime('%Y-%m-%d')
    dateold = dateold.strftime('%Y-%m-%d')
    #    date = datetime.date.today()
    rzv = Razvozka.objects.order_by('-date', 'date_id')
    cust = list(Customer.objects.order_by('name'))

    f_rzv0 = {}
    for r in rzv:
        if r.date not in f_rzv0:
            f_rzv0[r.date] = []
        f_rzv0[r.date].append(r)

    f_rzv2 = list(f_rzv0.items())
    paginator = Paginator(f_rzv2, 7)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    f_rzv = dict(page_obj.object_list)

    date_range = []
    for i in range(page_obj.paginator.num_pages):
        page_obj2 = paginator.get_page(i + 1)
        try:
            date_tmp = datetime.datetime.strptime(str(page_obj2.object_list[0][0]), '%Y-%m-%d').strftime('%d.%m.%Y')
            date_range.append([i + 1, 'до ' + date_tmp])
        except:
            date_range.append(['нет данных'])
    date_range.sort(reverse=True)
    rzv_len = []
    for rzv in f_rzv:
        rzv_len.append([rzv, len(f_rzv0[rzv])])
    context = {'f_rzv': f_rzv, 'datenew': datenew, 'navi': navi, 'cust': cust, 'page_obj': page_obj,
               'page_number': page_number, 'date_range': date_range, 'rzv_len': rzv_len, 'active1': 'active',
               'dateold': dateold}
    return render(request, 'razvozki/index.html', context)


def delete_rzv(request, id):
    razvozka = Razvozka.objects.get(id=id)
    razvozka.delete()
    return HttpResponseRedirect(reverse('razvozki:index'))

@csrf_exempt
def updaterecord_rzv(request):
    page_num = request.POST['page_number_upd']
    date = request.POST['date']
    date = datetime.datetime.strptime(date, '%Y-%m-%d').strftime('%Y-%m-%d')
    date_id = request.POST['date_id']
    address = request.POST['address']
    customer_name = request.POST['customer']
    contact = request.POST['contact']
    mappoint = request.POST['mappoint']
    to_do_take = request.POST['to_do_take']
    to_do_deliver = request.POST['to_do_deliver']
    try:
        rzv_id = request.POST['rzv_id']
        razvozka = Razvozka.objects.get(id=rzv_id)
        razvozka.address = address
        razvozka.contact = contact
        razvozka.map_point = mappoint
        razvozka.to_do_take = to_do_take
        razvozka.to_do_deliver = to_do_deliver
        razvozka.date = date
        razvozka.date_id = date_id
        date_create = razvozka.date_create
    except:
        date_create =datetime.date.today()
        razvozka = Razvozka(address=address, contact=contact, fulfilled=False, date=date, date_id=date_id,
                            map_point=mappoint, to_do_take=to_do_take, to_do_deliver=to_do_deliver,
                            date_create=date_create)

    customer_id = request.POST['customer_id']
    if customer_id != '':
        customer = Customer.objects.get(id=customer_id)
        razvozka.customer = customer
        razvozka.customer_name = customer.name
    else:
        razvozka.customer_name = customer_name
    return_goods_id = request.POST['upd_id']
    if return_goods_id != '':
        razvozka_return = Razvozka.objects.get(id=return_goods_id)
        razvozka.return_goods = razvozka_return
        razvozka.return_from = True
    else:
        razvozka.return_from = False
    date_until = request.POST['date_until']
    if date_until != '':
        razvozka.date_until = date_until
    elif date == '2100-01-01':
        date_until = date_create + datetime.timedelta(days=7)
        razvozka.date_until = date_until
    razvozka.save()
    if page_num != '':
        page_num = '?page=' + page_num
    return HttpResponseRedirect(reverse('razvozki:index') + page_num)


def main_rzv(request):
    template = loader.get_template('razvozki/main.html')
    return HttpResponse(template.render({}, request))


def customers(request):
    navi = 'customer'
    cust = Customer.objects.order_by('name')

    paginator = Paginator(cust, 30)  # Show 30.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    page_name = list(page_obj.object_list)[0].name + ' - ' + list(page_obj.object_list)[-1].name

    customer_range = []
    for i in range(page_obj.paginator.num_pages):
        page_obj2 = paginator.get_page(i + 1)
        customer_range.append([i + 1, list(page_obj2.object_list)[0].name + ' - ' + list(page_obj2.object_list)[-1].name])

    context = {'navi': navi, 'page_obj': page_obj, 'active2': 'active', 'page_name': page_name,
               'customer_range': customer_range}
    return render(request, 'razvozki/customers.html', context)


@transaction.atomic()
def cst_double_search(request):
    """
    looking for doubles
    :param request:
    :return: change color to danger
    """
    order = request.POST['order_doub']
    cust = Customer_clr.objects.all()
    for cst1 in cust:
        cst1.clr = ''
        if find_dubl_cst(cst1, cust)[0]:
            cst1.clr = 'text-danger'
        Customer_clr.objects.filter(id=cst1.id).update(clr=cst1.clr)
    context = {'order': order}
    return HttpResponseRedirect(reverse('razvozki:customers'), context)


def customers_clr(request):
    #    return

    # def customers_checks(request):
    cust = Customer.objects.order_by('name')
    razv = Razvozka.objects.order_by('-date')
    # add customers to Customer_clr if not exist
    for cst in cust:
        try:
            tmp = Customer_clr.objects.get(id=cst.id)
        except Customer_clr.DoesNotExist:
            tmp = None
        if tmp is None:
            cst_clr = cst.Customer_clr(id=cst.id, name=cst.name, address=cst.address, contact=cst.contact,
                                       mappoint=cst.mappoint, clr='text-secondary')
            cst_clr.save()
    ## end of adding Customer_clr

    # return Customer names if dissapeared
    for cst in cust:
        if cst.name == '':
            rr2 = Razvozka.objects.filter(customer_id=cst.id).first()
            if rr2 is not None:
                cst.name = rr2.customer_name
                cst.address = rr2.address
                cst.contact = rr2.contact
                #                cst.mappoint = rr2.mappoint
                cst.save()
    ## end of returning customers
    # collect customers from razvozki
    for rzv in razv:
        if rzv.customer is None and find_dubl_cst(rzv.customer, cust)[0]:
            new_customer = Customer_clr(name=rzv.customer_name, address=rzv.address,
                                        contact=rzv.contact, clr='text-secondary')
            new_customer.save()
            rzv.customer = new_customer
            rzv.save()
    return HttpResponseRedirect(reverse('razvozki:customers', args=['name']))


def cust_trim_replace(cst1, cst2):
    """
    :param cst1: first customer to compare
    :param cst2: second customer to compare
    :return:
    """
    cst1_name = cst1.name.replace('ИП ', '')
    cst1_name = cst1_name.replace(' ', '')
    cst1_name = cst1_name.replace('-', '')
    cst1_name = cst1_name.replace('.', '')
    cst1_name = cst1_name.replace(',', '')
    cst1_name = cst1_name.replace('"', '')
    cst1_name = cst1_name.replace('?', '')

    cst2_name = cst2.name.replace('ИП ', '')
    cst2_name = cst2_name.replace(' ', '')
    cst2_name = cst2_name.replace('-', '')
    cst2_name = cst2_name.replace('.', '')
    cst2_name = cst2_name.replace(',', '')
    cst2_name = cst2_name.replace('"', '')
    cst2_name = cst2_name.replace('?', '')

    cst1_address = cst1.address.replace('г.', '')
    cst1_address = cst1_address.replace(' ', '')
    cst1_address = cst1_address.replace('-', '')
    cst1_address = cst1_address.replace('.', '')
    cst1_address = cst1_address.replace(',', '')
    cst1_address = cst1_address.replace('?', '')

    cst2_address = cst2.address.replace('г.', '')
    cst2_address = cst2_address.replace(' ', '')
    cst2_address = cst2_address.replace('-', '')
    cst2_address = cst2_address.replace('.', '')
    cst2_address = cst2_address.replace(',', '')
    cst2_address = cst2_address.replace('?', '')

    return [cst1_name, cst1_address, cst2_name, cst2_address]


def find_dubl_cst(cst1, cust):
    """
    looking doubles in db
    :param cst1: element if have double
    :param cust: db in which searching element
    :return: True if cst1 in cust db
    """
    result = False
    cst_id = ''
    for cst2 in cust:
        cst1_name = cust_trim_replace(cst1, cst2)[0]
        cst1_address = cust_trim_replace(cst1, cst2)[1]

razvozki/templates/razvozki/add_cst.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Клиенты</title>
</head>
{% include 'razvozki/main.html' %}

<body>
<br><br>
<br>
<div class="container px-1">
  <div class="row row-cols-5">
    <div class="col-1 text-center fw-bold">Добавить</div>
    <div class="col text-center fw-bold">Клиент</div>
    <div class="col text-center fw-bold" >Адрес</div>
    <div class="col text-center fw-bold">Контакт</div>
    <div class="col text-center fw-bold">Добавить</div>
  </div>
</div>

<form action="addrecord_cst/" method="post">
{% csrf_token %}
<div class="container px-1" >
  <div class="row row-cols-5">
    <div class="col-1 text-center"><a href="{% url 'razvozki:customers' %}"><i class="bi bi-x-circle-fill" style="color:red"></i></a></div>
    <div class="col text-center"><input type="text" class="form-control" id="customer_name" placeholder="Клиент" name="name"></div>
    <div class="col text-center"><input type="text" class="form-control" id="address" placeholder="Адрес" name="address"></div>
    <div class="col text-center"><input type="text" class="form-control" id="contact" placeholder="Контакт" name="contact"></div>
    <div class="col text-center"><button type="submit" class="bi bi-check-circle-fill" style="color:green; background-color:white; border-style:none"></button></div>
  </div>
</div>
</form>
{% for cst in cust %}
<div class="container px-1">
  <div class="row row-cols-5">
    <div class="col-1 text-center"><i class="bi bi-plus-circle-fill" style="color:gray"></i></div>
    <div class="col border border-1">{{cst.name}}</div>
    <div class="col border border-1">{{cst.address}}</div>
    <div class="col border border-1">{{cst.contact}}</div>
    <div class="col border border-1 text-center"><i class="bi bi-x-circle-fill" style="color:gray"></i>
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" disabled>
        <label class="form-check-label" for="flexCheckDefault">
           объединить
        </label>
    </div>
  </div>
</div>
{% endfor %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

razvozki/templates/razvozki/admin.html
{% extends 'razvozki/main.html' %}
{% block title %}Администрирование{% endblock %}
{% block content %}
{% load static %}

<div class="row-auto p-2">
    <div class="col-auto text-success">
        Основная база: Развозки: {{razv_count}} Клиенты: {{customer_count}}
    </div>
</div>
<div class="row-auto p-2">
    <div class="col-auto text-danger">
        Временная база: Развозки: {{razv_count_imp}}
    </div>
</div>
<form id="import_csv" action="{% url 'razvozki:import_csv' %}" method="post">
{% csrf_token %}
<div class = "col-auto p-2">
<div class="input-group justify-content col-auto">
  <div class="custom-file text-success">
    Импорт из .csv (во временную базу)
    <label class="custom-file-label" for="ChoseCSV"></label>
    <input type="file" accept=".csv" class="custom-file-input col-auto border" id="ChoseCSV" name="Chosen">
  </div>
  <div class="input-group-append text-success bg-outline-success" >
    <label for="date_begin"> с: </label>
    <input type="date" id="date_begin" name="date_begin" style="color: green">
    <label for="date_end"> по: </label>
    <input type="date" id="date_end" name="date_end" style="color: green">
    <button class="btn btn-outline-danger" type="submit"> Выбрать </button>
  </div>
</div>
</div>
</form>
<div class="row align-left p-2">
        <div class="col-auto text-success">
        <form id="import_cust" action="{% url 'razvozki:import_cst' %}" method="post">
        {% csrf_token %}
            Сбор клиентов по базе
            <button class="btn btn-outline-success btn" type="submit">Получить клиентов из базы</button>
        </form>
        </div>
        <div class="col-auto text-danger">
        <form id="delete_all_cst" action="{% url 'razvozki:delete_all_cst' %}" method="post">
        {% csrf_token %}
            Стереть всех клиентов
            <button class="btn btn-outline-danger btn" type="submit">Стереть всех клиентов</button>
        </form>
        </div>
</div>
<div class="row align-left p-2">
        <div class="col-auto text-success">
        <form id="clean_cst" action="{% url 'razvozki:clean_cst' %}" method="post">
        {% csrf_token %}
            Уборка базы Клиентов (кавычки, "ИП", двойные пробелы)
            <button class="btn btn-outline-success btn" type="submit">Чистить Клиентов</button>
        </form>
        </div>
        <div class="col-auto text-success">
        <form id="clean_rzv" action="{% url 'razvozki:clean_rzv' %}" method="post">
        {% csrf_token %}
            Уборка базы Развозки (кавычки, "ИП", двойные пробелы)
            <button class="btn btn-outline-success btn" type="submit">Чистить развозки</button>
        </form>
        </div>
</div>

<form id="export_rzv" action="{% url 'razvozki:export_rzv' %}" method="post">
{% csrf_token %}
<div class = "col-auto p-2">
<div class="input-group justify-content col-auto">
  <div class="custom-file text-danger">
    Экспорт из временной в основную базу
    <label for="date_begin"> с: </label>
    <input type="date" id="date_begin_exp" name="date_begin_exp" style="color: red">
    <label for="date_end"> по: </label>
    <input type="date" id="date_end_exp" name="date_end_exp" style="color: red">
    <button class="btn btn-outline-danger" type="submit"> Экспорт </button>
  </div>
</div>
</div>
</form>


{% endblock %}

razvozki/templates/razvozki/double.html
{% extends 'razvozki/main.html' %}
{% block title %}Дубли{% endblock %}
{% block content %}

{% load static %}
<br>
<div class="container-fluid">
 <div class="row bg-success" style="--bs-bg-opacity: .3;" >
    <div class="col-auto border border-1">
        <div id="initial_un">
         <a href="javascript:unite_double();">
            <button type="button" class="btn btn-outline-success btn-sm">Слить</button>
        </a>
         <a href="javascript:upd_ln_double();">
             <button type="button" class="btn btn-outline-danger btn-sm">Изменить</button>
         </a>
        </div>
    <form id="unite_cst" action="{% url 'razvozki:unite_cst' %}" method="post">
    {% csrf_token %}
    <input type="hidden" id="order_un" name="order_un" value="{{order}}">
    <div id="final_un" style="display:none">
         <input type="hidden" id="cst_lv" name="cst_lv">
         <input type="hidden" id="cst_dt" name="cst_dt">
         <button type="submit" class="btn btn-success btn-sm">Подтвердить слияние</button>
        </a>
    </div>
    </form>
    </div>
    <div class="col-2 text-center fw-bold">
        <a href="{% url 'razvozki:double' 'name' %}" class="link-success"><i class="bi bi-caret-down-fill bi-success"></i> Клиент </a>
    </div>
    <div class="col text-center fw-bold" >
        <a href="{% url 'razvozki:double' 'address' %}" class="link-success"><i class="bi bi-caret-down-fill bi-success"></i> Адрес </a>
    </div>
    <div class="col text-center fw-bold">
        <a href="{% url 'razvozki:double' 'contact' %}" class="link-success"><i class="bi bi-caret-down-fill bi-success"></i> Контакт </a>
    </div>
    <div class="col-2 text-center fw-bold text-success">Yandex-Координата</div>
  </div>
  {% for cst in cust %}
  <div class="row " id="show_{{cst.id}}">
    <div class="col-auto border border-1">
        <input type="radio" class="btn-check" name="options_outlined_leave" id="success_outlined_{{cst.id}}" autocomplete="off" value="l_{{cst.id}}">
        <label class="btn btn-sm btn-outline-success" for="success_outlined_{{cst.id}}">Оставить</label>

        <input type="radio" class="btn-check" name="options_outlined_delete" id="danger_outlined_{{cst.id}}" autocomplete="off" value="d_{{cst.id}}">
        <label class="btn btn-sm btn-outline-danger" for="danger_outlined_{{cst.id}}">Убрать</label>
    </div>
    <div class="col-2 border border-1 {{cst.clr}}">{{cst.name}} </div>
    <div class="col border border-1 {{cst.clr}}" >{{cst.address}}</div>
    <div class="col border border-1 {{cst.clr}}">{{cst.contact}}</div>
    <div class="col-2 border border-1 text-center {{cst.clr}}">{{cst.mappoint}}</div>
  </div>
    <form id="update_cst" action="{% url 'razvozki:updaterecord_cst' %}" method="post">
    {% csrf_token %}
      <input type="hidden" id="order_up" name="order_up" value="{{order}}">
      <input type="hidden" id="page_number_upd" name="page_number_upd" value="">
      <div id="hide_{{cst.id}}" style="display:none">
      <div class="row " >
        <div class="col-auto border border-1">
            <button  form="update_cst" type="submit" class="btn btn-success btn-sm">Записать</button>
            <button onclick="javascript:upd_ln_double_reverse;" class="btn btn-danger btn-sm">Отмена</button>

        </div>
        <div class="col-2 border border-1">
            <input type="text" class="form-control {{cst.clr}}" placeholder="Клиент" name="cst_name" value="{{ cst.name }}">
            <input type="hidden" class="form-control {{cst.clr}}" placeholder="id" name="cst_id" value="{{ cst.id }}">
        </div>
        <div class="col border border-1"><textarea class="form-control {{cst.clr}}"  placeholder="Адрес" name="address">{{cst.address}}</textarea></div>
        <div class="col border border-1"><textarea class="form-control {{cst.clr}}"  placeholder="Контакт" name="contact">{{cst.contact}}</textarea></div>
        <div class="col-2 border border-1 text-center text-danger">
            <input type="text" class="form-control {{cst.clr}}"  placeholder="Координата" name="mappoint" value="{{cst.mappoint}}">
        </div>
      </div>
      </div>
    </form>
  {% endfor %}

<!-- </form> -->
</div>
{% endblock %}